name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Build release binary
      run: cargo build --release
    
    - name: Create release archive
      run: |
        mkdir -p dist
        cp target/release/confirm-pam dist/
        cd dist
        tar -czf confirm-pam-macos-amd64.tar.gz confirm-pam
        shasum -a 256 confirm-pam-macos-amd64.tar.gz > confirm-pam-macos-amd64.tar.gz.sha256
    
    - name: Create Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      with:
        files: |
          dist/confirm-pam-macos-amd64.tar.gz
          dist/confirm-pam-macos-amd64.tar.gz.sha256
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
