name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.1.1)'
        required: true
        type: string

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Get release info
      id: release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG="${{ github.event.release.tag_name }}"
        else
          TAG="${{ github.event.inputs.tag }}"
        fi
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        
        # Get the release asset URL and SHA256
        RELEASE_INFO=$(gh release view "$TAG" --json assets)
        echo "Release info: $RELEASE_INFO"
        
        # Get download URL (browserDownloadUrl)
        ASSET_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | contains("macos-amd64.tar.gz") and (.name | endswith(".tar.gz"))) | .url')
        echo "Asset URL: $ASSET_URL"
        
        # Convert to download URL
        DOWNLOAD_URL="https://github.com/azu/confirm-pam/releases/download/$TAG/confirm-pam-macos-amd64.tar.gz"
        echo "Download URL: $DOWNLOAD_URL"
        
        # Download and calculate SHA256
        curl -sL "$DOWNLOAD_URL" -o temp.tar.gz
        SHA256=$(shasum -a 256 temp.tar.gz | cut -d' ' -f1)
        rm temp.tar.gz
        
        echo "asset_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
        echo "sha256=$SHA256" >> $GITHUB_OUTPUT
        echo "version=${TAG#v}" >> $GITHUB_OUTPUT

    - name: Update Formula
      run: |
        # Update the formula file
        sed -i "s|url \".*\"|url \"${{ steps.release.outputs.asset_url }}\"|" Formula/confirm-pam.rb
        sed -i "s|sha256 \".*\"|sha256 \"${{ steps.release.outputs.sha256 }}\"|" Formula/confirm-pam.rb
        
        # Show the changes
        echo "Updated Formula:"
        cat Formula/confirm-pam.rb

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update Homebrew formula to ${{ steps.release.outputs.tag }}"
        title: "Update Homebrew formula to ${{ steps.release.outputs.tag }}"
        body: |
          Updates the Homebrew formula for release ${{ steps.release.outputs.tag }}
          
          - URL: ${{ steps.release.outputs.asset_url }}
          - SHA256: ${{ steps.release.outputs.sha256 }}
          
          This PR was automatically created by the update-homebrew workflow.
        branch: update-homebrew-${{ steps.release.outputs.version }}
        delete-branch: true
